### ISSUE TITLE
JULgame for Linux next ?

### ISSUE THREAD

**Issue by TERIIHUB** [Kyjor/JulGame.jl#3]
Hi Kyle,
Just wondering  if you'd be planning on doing some game development "tools/utility" for the Linux plateforms anytime in the future ?
Cheers,
/Terii

**Comment by Kyjor** [comment]
Hello, I'll be looking into this relatively soon. I am currently working on the julgame editor. Once I am done with that, I'll get started on this. I will post any updates here. Thank you.

**Comment by Kyjor** [comment]
I took a look today, and with some slight changes I was able to build out to linux. The only issue is that the build is very big (~8gb). For now, this will probably be all I can do, but I may be able to look into another building solution. This will probably be usable along with the editor. It will be able to be done in the next commit to the develop branch, but there will be some slight modifications when the editor is usable.

**Comment by TERIIHUB** [comment]
Thanks, Kyle, I would like to try to run that whatever size it is for now...let us know the 
link when avaialble :)

**Comment by Kyjor** [comment]
Okay. If you would like to try it now, you can build it from the source. If you would just like to try a build of julgame, it will be awhile as I will have to get the editor up and running first to do that. Either way, I can help you. Just let me know which you would prefer

**Comment by TERIIHUB** [comment]
Oh, no worry, I can wait till its ready then. ;)

**Comment by Kyjor** [comment]
Awesome. Thanks for your patience!

**Comment by Kyjor** [comment]
Just an update. Sadly it looks like I cannot use the same solution for the editor for linux as windows. I am looking into alternatives at the moment. https://ldtk.io/ looks like something that could integrate well as an alternative. I just do not have the bandwidth to create two separate editors for this project. What I will do is: I will continue working on the windows editor until it is in a good enough state to build. Once I do that, then I will work with ldtk to see how much functionality I can match from the windows editor. That will add some time. But I will continue to update here.

**Comment by TERIIHUB** [comment]
No worry, on the other hand i'm also investigating on any tools that could allows building of common office Xplateform apps (with some DB databinding interfaces) ... so I keep busy on that project too.
BTW - don't know if that could be an option to go for some Game dev but I've just found that web dev tools...just in case it could serves your project.
https://www.youtube.com/watch?v=g5V8rTvFDwo&t=3s

**Comment by Kyjor** [comment]
Hello, just wanted to give a little update. The first version of the editor has been released. It is very rough right now. I think you might be able to run it with wine. I can test that soon. I don't have any documentation at the moment, but plan on working on that in the coming weeks.

**Comment by TERIIHUB** [comment]
Thanks Kyle,


Will  give it an eyes when I can install wine (not too familiar with it sitll...)

Have a nice week end !


De : Kyle Conel ***@***.***>
À : Kyjor/JulGame.jl ***@***.***>
Sujet : Re: [Kyjor/JulGame.jl] JULgame for Linux next ? (Issue #3)
Date : 23/06/2023 15:33:48 Pacific/Tahiti
Copie à : Terii ***@***.***>;
   Author ***@***.***>


Hello, just wanted to give a little update. The first version of the editor has been released. It is very rough right now. I think you might be able to run it with wine. I can test that soon. I don't have any documentation at the moment, but plan on working on that in the coming weeks.

**Comment by Kyjor** [comment]
Long time, no see 😄 I've made some major progress in the way of the editor. The main issue I had was that ImGui for Julia had no SDL backend, which forced me to use two separate windows. One with ImGui, and one with SDL. For some reason, on Linux, that combination did not mesh well. I ended up creating the backend myself: https://github.com/Kyjor/ImGuiSDLBackend.jl. Theoretically, this should allow for linux support now. But now I have to make modifications to make the editor work with the game view all in one window. That will take some time. Once it is ready, I will update here and finally close this 😄  Sorry for the wait!

**Comment by Kyjor** [comment]
I know it's way too late, but I've been able to make progress on this. I just tested on Pop OS, and I was able to open and use the editor. Closing this now. 
![image](https://github.com/user-attachments/assets/c018d131-1a97-4fcd-9666-a98cbb1747c5)
