### ISSUE TITLE
Can't Open the Editor

### ISSUE THREAD

**Issue by SabeDoesThings** [Kyjor/JulGame.jl#39]
So I tried opening the editor by downloading the JulGame repo and going to here JulGame.jl-main\src\editor\Editor\src\ and then running julia Editor.jl and I get this

![image](https://github.com/Kyjor/JulGame.jl/assets/122580233/66a86499-d790-4c04-b79c-cf3cbcef8a02)

**Comment by Kyjor** [comment]
Did you use the repl? Did you run `include("Editor.jl")` or `julia ./Editor.jl`

**Comment by SabeDoesThings** [comment]
yes and both got the same error when in the repl.

**Comment by Kyjor** [comment]
I'll have to try and recreate this but I'm not sure what's going on here. It might be an environment issue. Is imgui installed to both the project and globally?

**Comment by achengli** [comment]
Could be OpenGL?
I have looked there, where the error log comes from and I see that they are precisely the ImGui modules that depend on OpenGL.
